-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 11:21:44 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Фильмы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Фильмы` (
  `id_фильма` INT NULL AUTO_INCREMENT,
  `название` VARCHAR(150) NOT NULL,
  `режиссёр` VARCHAR(100) NULL,
  `длительность_мин` INT NULL,
  `возрастной_рейтинг` VARCHAR(10) NULL,
  PRIMARY KEY (`id_фильма`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Залы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Залы` (
  `id_зала` INT NULL AUTO_INCREMENT,
  `номер` INT NOT NULL,
  `вместимость` INT NOT NULL,
  `тип` VARCHAR(20) NULL,
  PRIMARY KEY (`id_зала`),
  UNIQUE INDEX `номер_UNIQUE` (`номер` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Кресла`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Кресла` (
  `id_кресла` INT NULL AUTO_INCREMENT,
  `ряд` INT NOT NULL,
  `место` INT NOT NULL,
  `id_зала` INT NOT NULL,
  PRIMARY KEY (`id_кресла`, `id_зала`),
  INDEX `Залы_idx` (`id_зала` ASC) VISIBLE,
  CONSTRAINT `Залы`
    FOREIGN KEY (`id_зала`)
    REFERENCES `mydb`.`Залы` (`id_зала`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Сеансы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Сеансы` (
  `id_сеанса` INT NULL AUTO_INCREMENT,
  `дата` DATE NOT NULL,
  `время` TIME NOT NULL,
  `цена` DECIMAL(10,2) NULL,
  `id_фильма` INT NOT NULL,
  `id_зала` INT NOT NULL,
  PRIMARY KEY (`id_сеанса`, `время`, `id_фильма`, `id_зала`),
  INDEX `Фильмы_idx` (`id_фильма` ASC) VISIBLE,
  INDEX `Залы_idx` (`id_зала` ASC) VISIBLE,
  CONSTRAINT `Фильмы`
    FOREIGN KEY (`id_фильма`)
    REFERENCES `mydb`.`Фильмы` (`id_фильма`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Залы`
    FOREIGN KEY (`id_зала`)
    REFERENCES `mydb`.`Залы` (`id_зала`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Покупатели`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Покупатели` (
  `id_покупателя` INT NULL AUTO_INCREMENT,
  `имя` VARCHAR(100) NULL,
  `телефон` VARCHAR(20) NULL,
  PRIMARY KEY (`id_покупателя`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Билеты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Билеты` (
  `id_билета` INT NULL AUTO_INCREMENT,
  `статус` VARCHAR(20) NULL DEFAULT 'Свободен',
  `id_сеанса` INT NOT NULL,
  `id_кресла` INT NOT NULL,
  `id_покупателя` INT NOT NULL,
  PRIMARY KEY (`id_билета`, `id_покупателя`, `id_кресла`, `id_сеанса`),
  INDEX `Сеансы_idx` (`id_сеанса` ASC) VISIBLE,
  INDEX `Кресла_idx` (`id_кресла` ASC) VISIBLE,
  INDEX `Покупатели_idx` (`id_покупателя` ASC) VISIBLE,
  CONSTRAINT `Сеансы`
    FOREIGN KEY (`id_сеанса`)
    REFERENCES `mydb`.`Сеансы` (`id_сеанса`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Кресла`
    FOREIGN KEY (`id_кресла`)
    REFERENCES `mydb`.`Кресла` (`id_кресла`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Покупатели`
    FOREIGN KEY (`id_покупателя`)
    REFERENCES `mydb`.`Покупатели` (`id_покупателя`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
